/**
 * @module tools/routingEngine
 * @description Deterministic shortest-path routing engine for Unity Arena.
 *   Implements Dijkstra's algorithm on the venue's weighted, directional graph
 *   with real-time crowd-density awareness and accessibility filtering. All
 *   route calculations happen here on the server — Gemini may request a route
 *   via function calling, but the path is always computed deterministically by
 *   this module, never inferred or generated by the AI model.
 *
 * @pr-changes Introduced crowd-density cost multipliers (DENSITY_MULTIPLIERS),
 *   queue-penalty weighting per edge (QUEUE_PENALTY_PER_MINUTE), stair-avoidance
 *   soft penalty (STAIR_AVOIDANCE_PENALTY), and the avoidCrowds 1.5× amplifier.
 *   Also added elevator-outage exclusion logic and bidirectional edge building in
 *   buildAdjacency(). accessibilityStatus field added to returned RouteResult.
 *
 * @validation-review
 *   - Source and destination nodes are validated against ADJACENCY before running
 *     Dijkstra; unknown nodes throw NotFoundError immediately.
 *   - Infinity distance check ensures an unreachable-route error is surfaced to
 *     the caller rather than returning a broken/empty path.
 *   - elevatorOutages and closedEdges come from operationsState — they must be
 *     validated by the caller before being passed to calculateRoute().
 *   - crowdState zones are user-controlled (ops scenario) — not user-supplied.
 *
 * @scope-of-improvement
 *   - ADJACENCY is built once at module load from a static import; a live-reload
 *     mechanism is needed if the venue graph changes at runtime.
 *   - Elevator outage logic currently excludes ALL elevator edges when any outage
 *     is present; should be scoped to specific elevator IDs.
 *   - A* heuristic (using physical coordinates) could dramatically reduce
 *     search time for large graphs.
 *   - Route caching (RouteCache) is not applied here — the index.js exec wrappers
 *     could integrate cache look-up/store.
 *   - Walking speed (WALK_SPEED_MPM) is a single constant; it could be
 *     personalised per accessibility mode.
 *
 * @business-intent Provides safe, reliable navigation for up to 60,000+ fans
 *   inside Unity Arena. Accessibility-first routing is a legal and ethical
 *   requirement — wheelchair and step-free routing must never silently fall back
 *   to inaccessible paths. Crowd-aware routing directly reduces the risk of
 *   dangerous density build-ups in pinch-point corridors.
 */

import { randomUUID } from 'crypto';
import { PriorityQueue } from './priorityQueue.js';
import venue from '../data/venue.js';
import { NotFoundError } from '../utils/errors.js';

// #What — average pedestrian walking speed used to convert metres to minutes
/** Walking speed in metres per minute */
const WALK_SPEED_MPM = 80;

/**
 * Crowd density cost multipliers indexed by densityLevel string.
 * Higher multipliers make dense zones appear "more expensive" in Dijkstra,
 * steering routes away from them.
 * @type {Record<string, number>}
 * @business-intent Routing through critical-density zones increases stampede risk;
 *   these multipliers encode that safety concern into the path cost function.
 */
const DENSITY_MULTIPLIERS = {
  low: 1.0,
  moderate: 1.3,
  high: 1.8,
  critical: 2.5,
};

// #What — transforms queue wait time into a comparable edge cost unit (seconds-equivalent)
/** Penalty per minute of queue time added to edge cost */
const QUEUE_PENALTY_PER_MINUTE = 60;

// #Business-Intent — soft penalty avoids disabling edges entirely for stair preference,
//   preserving route availability when no alternative exists
/** Large stair penalty when avoidStairs is true but stairs not completely excluded */
const STAIR_AVOIDANCE_PENALTY = 500;

/**
 * Build an adjacency map from the venue graph edges (bidirectional).
 *
 * @description Iterates over every edge in the static venue graph and registers
 *   it in both directions so Dijkstra can traverse the graph in any direction.
 *   This is called once at module initialisation and cached as ADJACENCY.
 *
 * @returns {Map<string, Array<Object>>} Map from node ID to list of neighbour edge objects.
 *
 * @business-intent A bidirectional graph mirrors physical reality — a corridor
 *   passable from A to B is also passable from B to A (barring one-way restrictions
 *   which are encoded at the edge level, not here).
 */
function buildAdjacency() {
  // #What — seed every known node with an empty neighbour list to guarantee Map.get() safety
  const adj = new Map();
  for (const node of venue.graph.nodes) {
    adj.set(node, []);
  }

  // #What — push each edge into both directions so Dijkstra can traverse freely
  for (const edge of venue.graph.edges) {
    adj.get(edge.from)?.push({ ...edge, neighbor: edge.to });
    adj.get(edge.to)?.push({ ...edge, neighbor: edge.from });
  }
  return adj;
}

// #What — module-level singleton; built once at import time from the static venue data
// #Risk-Area — if venue data is ever hot-reloaded this cache becomes stale
const ADJACENCY = buildAdjacency();

/**
 * Get crowd density for a node from the crowd state zone map.
 *
 * @description Looks up the zone record for a given node ID. Falls back to
 *   low density / zero queue when the node is not tracked in the crowd state,
 *   so routing remains functional even for nodes outside active monitoring zones.
 *
 * @param {string} nodeId - Venue graph node identifier.
 * @param {Map<string, Object>} zoneMap - Pre-built lookup Map from zone.id → zone record.
 * @returns {{ densityLevel: string, queueMinutes: number }} Crowd data or safe defaults.
 *
 * @validation-note Falls back to 'low' density — callers must ensure zoneMap is
 *   populated from a fresh crowdState snapshot to prevent stale default usage.
 */
function getNodeCrowd(nodeId, zoneMap) {
  const zone = zoneMap.get(nodeId);
  // #What — return zone data if found, otherwise safe defaults so routing still works
  if (zone) return { densityLevel: zone.densityLevel, queueMinutes: zone.queueMinutes };
  return { densityLevel: 'low', queueMinutes: 0 };
}

/**
 * Check if an edge should be excluded from Dijkstra traversal.
 *
 * @description Applies four independent exclusion rules in order:
 *   wheelchair accessibility, step-free requirement, elevator outage, and
 *   explicitly closed edges. Returns true (exclude) on the first matching rule.
 *
 * @param {Object} edge - Venue graph edge object.
 * @param {Object} opts - Route options (from calculateRoute call).
 * @param {boolean} [opts.wheelchair] - Require wheelchair-accessible edges.
 * @param {boolean} [opts.stepFree] - Require step-free edges.
 * @param {string[]} [opts.elevatorOutages] - List of elevator IDs currently offline.
 * @param {Array<[string,string]>} [opts.closedEdges] - Edge pairs [from,to] to exclude.
 * @returns {boolean} True if the edge must be skipped.
 *
 * @risk-area Incorrect exclusion logic could route a wheelchair user through stairs,
 *   violating accessibility law. Any change here requires manual QA with
 *   accessibility test fixtures.
 */
function isEdgeExcluded(edge, opts) {
  // #Business-Intent — wheelchair users MUST only receive accessible edges; safety-critical
  if (opts.wheelchair && !edge.accessible) return true;

  // #Business-Intent — step-free requirement excludes ramps without step-free designation
  if (opts.stepFree && !edge.stepFree) return true;

  // #Uncertain — currently excludes ALL elevator edges when ANY outage exists;
  //   should be narrowed to only outage-affected elevator IDs in a future revision
  // @human-approval-required — elevator outage scope should be verified by venue ops team
  if (opts.elevatorOutages?.length && edge.requiresElevator) {
    return true;
  }

  // #What — check if this edge matches any of the explicitly closed [from, to] pairs
  if (opts.closedEdges?.length) {
    for (const [a, b] of opts.closedEdges) {
      if ((edge.from === a && edge.to === b) || (edge.from === b && edge.to === a)) return true;
    }
  }
  return false;
}

/**
 * Calculate the weighted traversal cost of an edge for Dijkstra's algorithm.
 *
 * @description Combines physical distance with crowd density, queue time, stair
 *   avoidance, and long-walk avoidance into a single numeric cost. Lower cost
 *   makes the edge more attractive during path selection.
 *
 * @param {Object} edge - Venue graph edge.
 * @param {Object} opts - Route preference options.
 * @param {boolean} [opts.avoidCrowds] - If true, amplify density penalty by 1.5×.
 * @param {boolean} [opts.avoidStairs] - If true, add STAIR_AVOIDANCE_PENALTY.
 * @param {boolean} [opts.avoidLongWalking] - If true, apply 1.1× distance multiplier.
 * @param {Map<string, Object>} zoneMap - Current crowd state keyed by node/zone ID.
 * @returns {number} Numeric path cost for this edge.
 *
 * @business-intent The cost function encodes multiple overlapping fan preferences
 *   (accessibility, comfort, safety) into a single decision variable, allowing
 *   the same Dijkstra pass to satisfy all of them simultaneously.
 *
 * @risk-area Changing weight constants here can inadvertently route crowds through
 *   dangerous areas. Any coefficient change should be load-tested against all
 *   venue scenarios before deployment.
 */
function edgeCost(edge, opts, zoneMap) {
  // #What — fetch crowd density for the destination node of this edge
  const { densityLevel, queueMinutes } = getNodeCrowd(edge.to, zoneMap);

  // #Business-Intent — avoidCrowds fans get an extra 1.5× penalty to steer them
  //   harder away from dense areas compared to a fan who did not select this option
  const crowdMult = opts.avoidCrowds
    ? (DENSITY_MULTIPLIERS[densityLevel] || 1.0) * 1.5
    : (DENSITY_MULTIPLIERS[densityLevel] || 1.0);

  // #What — base cost = physical distance scaled by crowd density
  let cost = edge.distance * crowdMult;

  // #What — add waiting time at destination as additional cost (queue penalty)
  cost += queueMinutes * QUEUE_PENALTY_PER_MINUTE;

  // #Business-Intent — soft stair penalty keeps stairs as fallback but discourages them
  if (opts.avoidStairs && edge.requiresStairs) {
    cost += STAIR_AVOIDANCE_PENALTY;
  }

  // #What — a uniform 10% distance premium for fans who prefer shorter walks
  if (opts.avoidLongWalking) {
    cost *= 1.1;
  }

  return cost;
}

/**
 * Run Dijkstra's algorithm on the Unity Arena venue graph and return a
 * fully-annotated RouteResult.
 *
 * @description This is the primary entry point of the routing engine.
 *   It validates input nodes, builds a crowd zone lookup, executes Dijkstra
 *   with preference-aware edge costs, reconstructs the shortest path, and
 *   assembles a rich result object including step-by-step directions,
 *   accessibility status, crowd warnings, and a verification flag.
 *
 * @param {Object} options - Routing configuration.
 * @param {string} options.from - Source node ID (must exist in venue graph).
 * @param {string} options.to - Destination node ID (must exist in venue graph).
 * @param {boolean} [options.wheelchair] - Require wheelchair-accessible route only.
 * @param {boolean} [options.stepFree] - Require step-free route only.
 * @param {boolean} [options.avoidStairs] - Apply soft penalty for stair edges.
 * @param {boolean} [options.avoidCrowds] - Amplify density penalty by 1.5×.
 * @param {boolean} [options.avoidLongWalking] - Apply 1.1× distance multiplier.
 * @param {string[]} [options.elevatorOutages] - IDs of elevators currently offline.
 * @param {Array<[string,string]>} [options.closedEdges] - Edge pairs to exclude.
 * @param {{ zones: Array<Object> }} [crowdState] - Live crowd state snapshot.
 * @returns {import('../types.js').RouteResult} Fully resolved route with steps, warnings, and metadata.
 * @throws {NotFoundError} If source or destination node is unknown, or no route exists.
 *
 * @risk-area This function is the safety-critical core of the fan navigation system.
 *   Bugs here can route fans into dangerous, inaccessible, or closed areas.
 *
 * @business-intent Ensures every fan receives a verified, up-to-date route that
 *   respects their accessibility needs and avoids crowd pinch points, reducing
 *   incident risk and improving fan experience.
 */
export function calculateRoute(options, crowdState) {
  const { from, to } = options;

  // #Risk-Area — validate node existence before any graph traversal; prevents
  //   silent failures on typos or stale node IDs from AI function-call arguments
  if (!ADJACENCY.has(from)) throw new NotFoundError(`Unknown start node: ${from}`);
  if (!ADJACENCY.has(to)) throw new NotFoundError(`Unknown destination node: ${to}`);

  // #What — convert zones array into a keyed Map for O(1) lookups during edge costing
  const zoneMap = new Map();
  if (crowdState?.zones) {
    for (const zone of crowdState.zones) {
      zoneMap.set(zone.id, zone);
    }
  }

  // ── Dijkstra initialisation ───────────────────────────────────────────────

  // #What — dist tracks the best-known cost to reach each node; starts at Infinity
  const dist = new Map();
  // #What — prev tracks which node we came from (for path reconstruction)
  const prev = new Map();
  // #What — prevEdge tracks the edge object used to reach each node
  const prevEdge = new Map();
  const pq = new PriorityQueue();

  for (const node of ADJACENCY.keys()) {
    dist.set(node, Infinity);
  }
  dist.set(from, 0);
  pq.push(from, 0);

  // ── Dijkstra main loop ────────────────────────────────────────────────────
  while (!pq.isEmpty()) {
    const current = pq.pop();
    // #What — early exit when destination is reached (Dijkstra guarantee: first pop = shortest)
    if (current === to) break;

    const currentDist = dist.get(current);
    const neighbors = ADJACENCY.get(current) || [];

    for (const edge of neighbors) {
      // #What — skip excluded edges based on accessibility/closure options
      if (isEdgeExcluded(edge, options)) continue;

      const cost = edgeCost(edge, options, zoneMap);
      const newDist = currentDist + cost;

      // #What — relax the edge if we found a cheaper path to the neighbour
      if (newDist < dist.get(edge.neighbor)) {
        dist.set(edge.neighbor, newDist);
        prev.set(edge.neighbor, current);
        prevEdge.set(edge.neighbor, edge);
        pq.push(edge.neighbor, newDist);
      }
    }
  }

  // #Risk-Area — Infinity means the destination is unreachable under current constraints;
  //   must surface a user-friendly error, not an empty result
  if (dist.get(to) === Infinity) {
    throw new NotFoundError(
      `No accessible route found from ${from} to ${to} with the selected preferences. Please try different accessibility options or speak to a venue staff member.`,
    );
  }

  // ── Path reconstruction ───────────────────────────────────────────────────

  // #What — walk backwards through prev map from destination to source, then reverse
  const nodes = [];
  let cur = to;
  while (cur) {
    nodes.unshift(cur);
    cur = prev.get(cur);
  }

  // ── Build step-by-step directions ─────────────────────────────────────────
  const steps = [];
  let totalDistance = 0;
  const avoidedZones = [];
  const warnings = [];

  for (let i = 0; i < nodes.length - 1; i++) {
    const edgeKey = nodes[i + 1];
    const edge = prevEdge.get(edgeKey);
    if (!edge) continue;

    totalDistance += edge.distance;

    // #What — generate crowd density warnings for high/critical zones on the path
    const zoneCrowd = getNodeCrowd(nodes[i + 1], zoneMap);
    if (zoneCrowd.densityLevel === 'high' || zoneCrowd.densityLevel === 'critical') {
      // #Business-Intent — warn fans proactively rather than routing them into a dangerous zone silently
      const zoneName = nodes[i + 1].replace(/-/g, ' ');
      warnings.push(`Area ahead (${zoneName}) is ${zoneCrowd.densityLevel} density. Allow extra time.`);
      avoidedZones.push(nodes[i + 1]);
    }

    steps.push({
      from: nodes[i],
      to: nodes[i + 1],
      description: describeStep(nodes[i], nodes[i + 1], edge),
      type: edge.type,
      distanceMeters: edge.distance,
    });
  }

  // #What — append a generalised elevator outage warning when any outage is active
  if (options.elevatorOutages?.length) {
    warnings.push('One or more elevators are currently out of service. This route avoids affected elevators.');
  }

  // ── Accessibility status resolution ───────────────────────────────────────

  // #Business-Intent — clearly communicates the accessibility quality of the returned route
  //   so fans and ops staff can make informed decisions
  let accessibilityStatus = 'fully-accessible';
  const hasStairEdge = steps.some((s) => s.type === 'stairs');
  const hasElevatorEdge = steps.some((s) => s.type === 'elevator');
  if (hasStairEdge) accessibilityStatus = 'not-accessible';
  else if (hasElevatorEdge && options.elevatorOutages?.length) accessibilityStatus = 'partially-accessible';

  // #What — capture the crowd snapshot version so consumers can detect stale data
  const snapshotVersion = crowdState?.zones?.[0]?.snapshotVersion || 'unknown';

  // @hallucination-guard — verified: true signals this route was computed deterministically,
  //   not generated or inferred by Gemini
  return {
    routeId: randomUUID(),
    nodes,
    steps,
    distanceMeters: totalDistance,
    estimatedMinutes: Math.ceil(totalDistance / WALK_SPEED_MPM),
    accessibilityStatus,
    avoidedZones: [...new Set(avoidedZones)], // #What — deduplicate zones that appear multiple times on the path
    warnings,
    verified: true,
    snapshotVersion,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Generate a human-readable step description for a route segment.
 *
 * @description Selects the appropriate natural-language template based on the
 *   edge type (stairs, elevator, ramp, external walk, or plain walk). Used
 *   to populate the `description` field of each step in RouteResult.
 *
 * @param {string} from - Source node ID.
 * @param {string} to - Destination node ID.
 * @param {Object} edge - Edge object with `type` and `distance` fields.
 * @returns {string} Human-readable instruction for this route segment.
 *
 * @business-intent Clear, plain-English step descriptions are essential for
 *   fans who may be unfamiliar with the venue layout, especially during
 *   high-stress situations like evacuations or medical emergencies.
 */
function describeStep(from, to, edge) {
  const fromLabel = formatNodeLabel(from);
  const toLabel = formatNodeLabel(to);

  // #What — each branch provides a contextually-appropriate instruction string
  if (edge.type === 'stairs') return `Take the stairs from ${fromLabel} to ${toLabel} (${edge.distance}m)`;
  if (edge.type === 'elevator') return `Take the elevator from ${fromLabel} to ${toLabel}`;
  if (edge.type === 'ramp') return `Follow the ramp from ${fromLabel} to ${toLabel} (${edge.distance}m)`;
  if (edge.type === 'external') return `Exit the venue and proceed to ${toLabel} (approximately ${edge.distance}m)`;
  return `Walk from ${fromLabel} to ${toLabel} (${edge.distance}m)`;
}

/**
 * Convert an internal hyphenated node ID to a title-cased human-readable label.
 *
 * @description Replaces hyphens with spaces and capitalises the first letter of
 *   each word, converting e.g. 'zone-north-concourse' to 'Zone North Concourse'.
 *
 * @param {string} id - Internal node ID.
 * @returns {string} Display-friendly label.
 *
 * @business-intent Node IDs are machine-friendly slugs; fans need natural
 *   place names for navigation instructions.
 */
function formatNodeLabel(id) {
  return id
    .replace(/-/g, ' ')
    // #What — capitalise first character of every space-separated word
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
